[project]
name = "marimo-github-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastexcel>=0.16.0",
    "marimo>=0.17.7",
    "polars>=1.35.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]
